version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/app
#      - /app/.venv
#    command: bash -c "poetry run alembic upgrade head &&
#             poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
#
#    env_file:
#      - .env
#    depends_on:
#      - db

volumes:
  db_value:
